<div id="page-wrapper">
    <div class="panel panel-info">
        <div class="panel-heading">
            <h3 class="panel-title">Create a decision analysis</h3>
        </div>
        <div class="panel-body">
            <div>Write down the parameters that will affect your decision</div><hr>

            <div id="parameterInput">
                <form class="parameterForm">
                    <ul>
                    <!--<label>Type</label><input type="text" class="parameterType"/>-->
                        <li><input type="text" class="parameterName" placeholder="NOM"/></li>
                        <li><input type="text" class="parameterValue" placeholder="VALUE"/></li>
                        <li><input type="text" class="parameterMinValue" placeholder="MIN VALUE"/></li>
                        <li><input type="text" class="parameterMaxValue" placeholder="MAX VALUE"/></li>
                        <li><input type="text" class="parameterUnit" placeholder="UNITS"/></li>
                        <li><button type="submit" value="">Add Parameter</button></li>
                    </ul>
                </form>
            </div>
            <hr>
            <div>
                List of parameters
            </div>
        </div>
    </div>
</div>