<div id="page-wrapper" xmlns="http://www.w3.org/1999/html">
    <div class="panel panel-info">
        <div class="panel-heading">
            <h3 class="panel-title">Create a decision analysis</h3>
        </div>
        <div class="panel-body">
            <div>Write down the parameters that will affect your decision</div><hr>

            <div>
                <form class="row" id="parameterForm">
                    <div class="col-xs-12">
                        <div class="form-group col-xs-4">
                            <label class="control-label">PARAMETER NAME</label>
                            <input type="text" class="form-control col-xs-3 parameterName" placeholder="NAME" required />
                        </div>
                        <div class="form-group col-xs-4">
                            <label class="control-label">VALUE</label>
                            <input type="text" class="form-control parameterMinValue" placeholder="MIN VALUE" data-parsley-type="number" required/>
                            <input type="text" class="form-control parameterMaxValue" placeholder="MAX VALUE" default-value="10" data-parsley-type="number" required/>
                        </div>
                        <div class="form-group col-xs-4">
                            <label class="control-label">UNIT</label>
                            <input type="text" class="form-control parameterUnit" placeholder="UNITS"/>
                        </div>
                    </div>
                    <div class="col-xs-12">
                        <input type="submit" class="btn btn-default" id="addParameter" name="addParameter"/>
                    </div>
                </form>
            </div>
            <hr>


            <div>
                <h4>Make your decision!</h4><hr>
                    <form class="row" id="decisionForm" data-parsley-validate>
                        <div class="form-group col-xs-4">
                            <label class="control-label">NOM</label>
                            <input type="text" class="form-control col-xs-3 decisionName" placeholder="NOM" required/>
                        </div>
                        <input type="submit" class="btn btn-default" id="getAllParametersData" value="Create your decision"></button>
                    </form>

                <div id="parametersList">
                </div>
            </div>
        </div>
    </div>
</div>


