<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Decision Helper</title>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . './css/bootstrap-theme.min.css')
        ->prependStylesheet($this->basePath() . './bower_components/font-awesome/css/font-awesome.min.css')
        ->prependStylesheet($this->basePath() . './bower_components/font-awesome/css/font-awesome.min.css')
        ->prependStylesheet($this->basePath() . './css/bootstrap.min.css')
        ->prependStylesheet($this->basePath() . './css/style.css')
        ->prependStylesheet($this->basePath() . './bower_components/sb-admin-v2/css/sb-admin.css')
        ->prependStylesheet($this->basePath() . './bower_components/parsleyjs/src/parsley.css')?>
</head>
<body>
<div class="container">

    <nav class="navbar navbar-default navbar-fixed-top" role="navigation" style="margin-bottom: 0;">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="index.html"><b>DECISION HELPER</b></a>
        </div>
        <!-- /.navbar-header -->

        <ul class="nav navbar-top-links navbar-right">
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-envelope fa-fw"></i>  <i class="fa fa-caret-down"></i>
                </a>

                <!-- /.dropdown-messages -->
            </li>
            <!-- /.dropdown -->
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-tasks fa-fw"></i>  <i class="fa fa-caret-down"></i>
                </a>

                <!-- /.dropdown-tasks -->
            </li>
            <!-- /.dropdown -->
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-bell fa-fw"></i>  <i class="fa fa-caret-down"></i>
                </a>

                <!-- /.dropdown-alerts -->
            </li>
            <!-- /.dropdown -->
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
                </a>
                <ul class="dropdown-menu dropdown-user">
                    <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                    </li>
                    <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                    </li>
                    <li class="divider"></li>
                    <li><a href="login.html"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                    </li>
                </ul>
                <!-- /.dropdown-user -->
            </li>
            <!-- /.dropdown -->
        </ul>
        <!-- /.navbar-top-links -->

        <div class="navbar-default navbar-static-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav" id="side-menu">
                    <li class="sidebar-search">
                        <!-- /input-group -->
                    </li>
                    <li>
                        <a href="./"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                    </li>
                    <li>
                        <a href="./create"><i class="fa fa-edit fa-fw"></i> Create decision</a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> Charts</a>
                        <!-- /.nav-second-level -->
                    </li>
                    <li>
                        <a href="tables.html"><i class="fa fa-table fa-fw"></i> Tables</a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-files-o fa-fw"></i> Sample Pages</a>
                    </li>
                </ul>
                <!-- /#side-menu -->
            </div>
            <!-- /.sidebar-collapse -->
        </div>

        <!-- /.navbar-static-side -->
    </nav>
    <div>
        <?php echo $this->content; ?>
    </div>


</div>
<!--<div class="container">
    <?php /*echo $this->content; */?>
</div>-->


<script src="./js/jquery.min.js"></script>
<script src="./js/bootstrap.min.js"></script>
<script src="./js/decision/create.js"></script>
<script src="./bower_components/parsleyjs/dist/parsley.js"></script>
<script src="./bower_components/echarts/build/dist/echarts.js"></script>
<script src="./bower_components/echarts/build/dist/echarts-all.js"></script>-->
<!--<script src="http://echarts.baidu.com/build/dist/echarts.js"></script>-->
<!--<script type="text/javascript">
    // configure for module loader
    require.config({
        paths: {
            echarts: './bower_components/echarts/build/dist'
        }
    });

    // use
    require(
        [
            'echarts',
            'echarts/chart/radar' // require the specific chart type
        ],
        function (ec) {
            // Initialize after dom ready
            var myChart = ec.init(document.getElementById('main'));


            option = {
                title : {
                    text: '（Budget vs spending）',
                    subtext: ''
                },
                tooltip : {
                    trigger: 'axis'
                },
                legend: {
                    orient : 'vertical',
                    x : 'right',
                    y : 'bottom',
                    data:['（Allocated Budget）','（Actual Spending）']
                },
                toolbox: {
                    show : true,
                    feature : {
                        mark : {show: true},
                        dataView : {show: true, readOnly: false},
                        restore : {show: true},
                        saveAsImage : {show: true}
                    }
                },
                polar : [
                    {
                        indicator : [
                            { text: '（sales）', max: 6000},
                            { text: '（Administration）', max: 16000},
                            { text: '（Information Techology）', max: 30000},
                            { text: '（Customer Support）', max: 38000},
                            { text: '（Development）', max: 52000},
                            { text: '（Marketing）', max: 25000}
                        ]
                    }
                ],
                calculable : true,
                series : [
                    {
                        name: '（Budget vs spending）',
                        type: 'radar',
                        data : [
                            {
                                value : [4300, 10000, 28000, 35000, 50000, 19000],
                                name : '（Allocated Budget）'
                            },
                            {
                                value : [5000, 14000, 28000, 31000, 42000, 21000],
                                name : '（Actual Spending）'
                            }
                        ]
                    }
                ]
            };

            // Load data into the ECharts instance
            myChart.setOption(option);
        }
    );
</script>
-->
<!-- DataTable Javascript -->
</body>
</html>


