<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Decision Helper</title>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
        ->prependStylesheet($this->basePath() . '/bower_components/font-awesome/css/font-awesome.min.css')
        ->prependStylesheet($this->basePath() . '/bower_components/font-awesome/css/font-awesome.min.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ->prependStylesheet($this->basePath() . '/css/style.css')
        ->prependStylesheet($this->basePath() . '/bower_components/sb-admin-v2/css/sb-admin.css')
        ->prependStylesheet($this->basePath() . '/bower_components/parsleyjs/src/parsley.css')
        ->prependStylesheet($this->basePath() . '/bower_components/datatables/media/css/jquery.dataTables.css')?>
</head>
<body>
<div class="container">

    <nav class="navbar navbar-default navbar-fixed-top" role="navigation" style="margin-bottom: 0;">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="index.html"><b>DECISION HELPER</b></a>
        </div>
        <!-- /.navbar-header -->

        <ul class="nav navbar-top-links navbar-right">
            <li class="dropdown">
                <a href="<?php echo $this->url('home', array('action'=>'index'));?>"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
            </li>
            <!-- /.dropdown -->
            <li class="dropdown">
                <a href="<?php echo $this->url('create', array('action'=>'create'));?>"><i class="fa fa-edit fa-fw"></i> Create decision</a>
            </li>
            <li class="dropdown">
                <a href="<?php echo $this->url('table', array('action'=>'table'));?>"></i> Tables</a>
            </li>
            <li class="dropdown">
                <a href="#"><i class="fa fa-files-o fa-fw"></i> Sample Pages</a>
            </li>
            <!-- /.dropdown -->
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-bell fa-fw"></i>  <i class="fa fa-caret-down"></i>
                </a>

                <!-- /.dropdown-alerts -->
            </li>
            <!-- /.dropdown -->
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
                </a>
                <ul class="dropdown-menu dropdown-user">
                    <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                    </li>
                    <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                    </li>
                    <li class="divider"></li>
                    <li><a href="login.html"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                    </li>
                </ul>
                <!-- /.dropdown-user -->
            </li>
            <!-- /.dropdown -->
        </ul>
        <!-- /.navbar-top-links -->



        <!-- /.navbar-static-side -->
    </nav>
    <div>
        <?php echo $this->content; ?>
    </div>


</div>


<script src="/js/jquery.min.js"></script>
<script src="/js/bootstrap.min.js"></script>
<script src="/bower_components/datatables/media/js/jquery.dataTables.js"></script>
<script src="/js/decision/create.js"></script>
<script src="/js/decision/table.js"></script>
<!--<script src="./js/decision/chart.js"></script>-->
<!--<script src="/bower_components/parsleyjs/dist/parsley.js"></script>
<script src="/bower_components/echarts/build/dist/echarts.js"></script>
<script src="/bower_components/echarts/build/dist/echarts-all.js"></script>
<script src="./js/decision/chart.js"></script>-->
<script src="/bower_components/parsleyjs/dist/parsley.js"></script>
<script src="/bower_components/echarts/build/dist/echarts.js"></script>
<script src="/bower_components/echarts/build/dist/echarts-all.js"></script>
</body>
</html>


