<div id="page-wrapper">
    <div class="panel panel-info">
        <div class="panel-heading">
            <h3 class="panel-title">Let's fill our parameter table</h3>
        </div>
        <div class="panel-body">
            <!--datatable to put here-->
            <table cellpadding="0" cellspacing="0" border="0" class="display" id="parameterTable">
                <thead >
                    <?php
                    $i = 0;
                    foreach ($this->parameters as $parameter) {
                        echo
                            '<th>'.
                                '<div class="">'.$parameter->getParameterName().'</div>'.
                                '<div>min : '.$parameter->getParameterMinValue().'</div>'.
                                '<div>max : '.$parameter->getParameterMaxValue().'</div>'.
                            '</th>';
                        $i++;
                    }
                    ?>
                </thead>
                <tbody>
                <tr>
                    <?php
                    $i = 0;
                    foreach ($this->parameters as $parameter) {
                        echo
                            '<td>
                                <input type="number" class="form-control parameterValue"
                                parameterId="'.$parameter->getParameterId().'"
                                parameterName="'.$parameter->getParameterName().'"
                                parameterMinValue="'.$parameter->getParameterMinValue().'"
                                parameterMaxValue="'.$parameter->getParameterMaxValue().'" />
                            </td>';
                        $i++;
                    }
                    ?>
                </tr>
                </tbody>
            </table>
            <div class="btn-toolbar">
                <button class="btn btn-default saveParametersInput">PROCESS VALUES</button>
                <button class="btn btn-default addRow">ADD A ROW</button>
            </div>
            <hr>
            <div>
                <button class="btn btn-default" id="chartGeneration">RADAR IT!</button>
            </div>
        </div>
        <div>

        </div>
    </div>
    <div class="panel panel-info">
        <div class="panel-heading">
            <h3 class="panel-title">Your radar</h3>
        </div>
        <div class="panel-body">
            <div id="main" style="height:400px;"></div>

        </div>
        <div>

        </div>
    </div>
</div>





<!--<div class="modal fade" id="myModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Modal title</h4>
            </div>
            <div class="modal-body">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        <h3 class="panel-title">Your radar</h3>
                    </div>
                    <div class="panel-body">
                        <div id="main" style="height:400px;"></div>

                    </div>
                    <div>

                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>-->



