<div id="page-wrapper">
    <div class="panel panel-info">
        <div class="panel-heading">
            <h3 class="panel-title">Let's fill our parameter table</h3>
        </div>
        <div class="panel-body">
            <!--datatable to put here-->
            <table cellpadding="0" cellspacing="0" border="0" class="display" id="parameterTable">
                <thead>
                    <?php
                    $i = 0;
                    foreach ($this->parameters as $parameter) {
                        echo '<th>'.$parameter->getParameterName().'</th>';
                        $i++;
                    }
                    ?>
                    <th>Save</th>
                </thead>
                <tbody>
                <tr>
                    <?php
                    $i = 0;
                    foreach ($this->parameters as $parameter) {
                        echo '<td><input type="number" class="form-control"></td>';
                        $i++;
                    }
                    ?>
                    <td><button class="btn btn-default saveParametersInput">SAVE</button></td>
                </tr>
                </tbody>
            </table>
        </div>
        <div>

        </div>
    </div>
</div>